include:
  - bnn.yaml

model:
  name: pv_usibnn

data:
  lookback: 16
  features:
    history:
      - AC_POWER
    weather:
      - IRRADIATION
      - AMBIENT_TEMPERATURE
      - MODULE_TEMPERATURE
      - hour_sin
      - hour_cos
      - dayofyear_sin
      - dayofyear_cos
      - is_generation_time
    direct:
      - AC_POWER
    target: AC_POWER

training:
  early_stopping:
    metric: val_generation_nrmse
