name: pv_usibnn_recursive_4h_generation_optuna
base_config: ../models/bnn/pv_usibnn_recursive_4h.yaml
output_dir: outputs
study_name: pv_usibnn_recursive_4h_generation_optuna
runner: recursive_bnn_4h
direction: minimize
metric: val_generation_nrmse
n_trials: 50

search_space:
  lr:
    type: log_float
    low: 0.0001
    high: 0.001
  kl_beta:
    type: log_float
    low: 0.0000001
    high: 0.0001