include:
  - lstm.yaml

model:
  hidden_dim: 32

data:
  lookback: 16
  horizon: 16
  features:
    history:
      - AC_POWER
    weather:
      - IRRADIATION
      - AMBIENT_TEMPERATURE
      - MODULE_TEMPERATURE
      - hour_sin
      - hour_cos
      - dayofyear_sin
      - dayofyear_cos
      - is_generation_time
    direct:
      - AC_POWER
    target: AC_POWER
